default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  pool: 5
  timeout: 5000

development:
  <<: *default

  database: ol_spam_development

test:
  <<: *default
  database: ol_spam_test

production:
  <<: *default
  database: ol_spam_production
 
